apiVersion: v1
kind: Pod
metadata:
  name: ngina-pod
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"