apiVersion: v1
kind: Pod
metadata:
  name: namespace-redis
  labels:
    name: myapp-redis
  namespace: dev
spec:
  containers:
  - name: redis
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: <Port>
